# Site settings
title: SYAHMI FAUZI .COM @ SF
email: brosyahmifauzi.gmail.com
description: > # Multiline description..
  Syahmi is a self-taught front-end web developer
  from Malaysia.. This is his personal website..
  Also, a blog..

# Uncomment 'baseurl' and 'url' when deploy..
# baseurl: ""
url: "https://www.syahmifauzi.com"
baseurl: "/sfv2"
local: "http://localhost:3000"

facebook_username: brosyhmi
instagram_username: brosyhmi
twitter_username: brosyhmi
github_username: syahmifauzi

# Build settings..
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/ # just pretty
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md", "offline.txt"]
